### ISSUE TITLE
POST/GET Request Parser

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/reporter#1]
We will need something to parse the POST/GET requests. For starters, we can assume its csv because that is fast and easy. In the long run, we may want to make this functionality modular with a well-defined interface so that other on-premise people can implement their own in case they have some exotic format.

**Comment by kdiluca** [comment]
Prototype is half done.  I still need to add logic for POST requests.  This is done within Valhalla/tools

**Comment by kdiluca** [comment]
status: I'm able to read a gpx file using our matcher_service.py and parse the data into the following:

“trace”: [ {“lat”:39.7777,”lon”:-76.5555,”time”:1111},
{“lat”:39.778,”lon”:-76.556,”time”:1112},
{“lat”:39.778,”lon”:-76.556,”time”:1113},
{“lat”:39.778,”lon”:-76.556,”time”:1114},
{“lat”:39.778,”lon”:-76.556,”time”:1115},
{“lat”:39.778,”lon”:-76.556,”time”:1116},
{“lat”:39.778,”lng”:-76.556,”time”:1117}]

TODOs today: Split the trace into 1 minute chunks to pass to the Valhalla matching function.
