### ISSUE TITLE
collect statistics on match failures

### ISSUE THREAD

**Issue by drewda** [opentraffic/reporter#34]
Collect the number of match failures by tile and send to [centralized Datastore](https://github.com/opentraffic/datastore) for aggregation and analysis.

This can help us to identify regions where there may be problems with OSMLR segment coverage, OSM tagging, or the map-matching process itself.

**Comment by dnesbitt61** [comment]
@kevinkreiser just pointed out that we don't know "tiles" at the segment matcher. We discussed possibly sending back wayIds and a lat,lon for traces (or parts of traces) that match to roads that do not have OSMLR segments. Any sort of "tiling" would have to be done by the Datastore/query API.

**Comment by drewda** [comment]
https://docs.google.com/document/d/1TXHIhPfXz_YD2_a6A9VmXVXw75jy63R-_ULSDRKcT54/edit

**Comment by dnesbitt61** [comment]
Match statistics will take 2 forms:
Logging to std out: this includes segment match information (including wayids of segments that are matched but not reported on) and a list of segments that will be aggregated and potentially sent to Datastore.
Aggregated stats: the Reporter will track statistics on number of successful matches, number of matches that include discontinuities (invalid matches), number of matches with errors (exceed speed threshold, other errors)

**Comment by drewda** [comment]
closed by #72
