### ISSUE TITLE
be robust to single point input

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/reporter#36]
currently the reporter assumes you are going to give it more than one point at a time. at the same time it also, if some of the end of your trace wasnt used, will store this information in redis to use with your next request. we can extend this logic a bit to allow for requests down to the single point per trace level. to do so we just need to add a bit of logic already found in the GRAB processing script:

* append input to partial from redis as normal (no extra implementation needed)
* if there arent enough points in the trace or there isnt enough time passed
  * then put the appended trace back into redis and return
* else do matching as normal and store partial as normal

decent values for the if condition above can be taking from the prior processing script. there should be one note here that we do expire stuff in redis after 5 minutes or so. this means that if you say give me 3 points and i just keep those in redis and dont match them. then you wait 5 minutes before giving me the rest of the 50 points needed to do matching then we'll lose those 3 points. this basically assures that clients are being timely when sending us stuff

**Comment by drewda** [comment]
WIP: #38

**Comment by kevinkreiser** [comment]
we still need to work on tweaking the values but they've now moved into the flink job. i'll open a new issue for making those values configurable.
