### ISSUE TITLE
Changes to Support Intersection Transition Times

### ISSUE THREAD

**Issue by dnesbitt61** [opentraffic/reporter#37]
Proposal:

Change from sending prior OSMLR segment to sending next OSMLR segment. When crossing an internal intersection edge, roundabout, or turn channel (which do not have OSMLR segments at this time) the Reporter will not output until either the matched path enters an OSMLR segment or enters a road without OSMLR segment (that is not internal intersection, roundabout, or turn channel). null is sent as the next OSMLR segment if the matched path enters a "local" road.

Set the end time as the time the next OSMLR segment is entered. If there is no next OSMLR segment then the end time is the time at the end of the current OSMLR segment.

Send length as the length of the matched segment plus the length along any internal intersection edges, roundabout edges, or turn channels used to get to the next OSMLR segment.

**Comment by drewda** [comment]
closed by https://github.com/opentraffic/reporter/pull/71
