### ISSUE TITLE
Ephemeral Cache Storage

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/reporter#4]
We need to figure out what exactly is going to go into the Redis cache, how we update it, and what we need to get back out of it.

**Comment by kdiluca** [comment]
After completing https://github.com/valhalla/valhalla/issues/551, we will be able to store and access/merge the partial shape in Redis via the start and end indexes.
uuid, portion of shape based on segment matcher indices & timestamp of last point (from gpx input trace)
