### ISSUE TITLE
Identify Threshold Logic for Reporting Segment + Next Segment

### ISSUE THREAD

**Issue by dnesbitt61** [opentraffic/reporter#43]
Need to determine when it is proper to output a traffic report. Since the report needs to include the next segment (if any) for intersection transition reporting, we need to make sure the match probability is such that the next segment is truly on the matched path. Might involve some time and distance thresholds that need to be exceeded so that we are fairly sure the matched path will not change based on future GPS locations.

**Comment by dnesbitt61** [comment]
Starting with a configurable threshold in seconds. Defaults to 15 sec.

**Comment by drewda** [comment]
closed by #71
