### ISSUE TITLE
Simulation and Testing Framework

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/reporter#48]
As a basis for testing the reporter it would be good to measure the impacts of changes we are making as we make them. Currently our approach to this is spread through libvalhalla as well as reporter ci. @kpwebb suggested a much more practical and straightforward way for us to get a quantitative measure of this though.

The basis of the idea is as follows:

* **plot a route**: have a routing engine plot a route returning per edge attribution (what traffic segments and what shape)
* **simulate a trace**: use the shape to simulate a sample trace by adding noise to the data. unevenly sample in space along the shape, offset from the shapes geometry, include fluctuations in horizontal accuracy and assign timestamps that will allow for validating speed
* **match**: submit the simulated trace to the traffic matcher to get back the result
* **validate**: check that what we did to the simulated trace affected the output in the desired way and report some statistics. we should see speeds that make sense within a threshold based on the times we assigned and we should see the same sequences of osmlr segments and non segments as we did on the original path

To accomplish the following, one would most likely add to the libvalhalla python bindings the ability to get a path and the attributes noted above (step 1). Then the reporter could be modified to do the remaining steps for some number of iterations.

**Comment by drewda** [comment]
notes and planning doc: https://docs.google.com/document/d/1od9g_ilkRQNiG_2qsmxU_NA_XqxFQ9bLfCF7ZiVQjgs/edit

**Comment by drewda** [comment]
Previous related work by @kpwebb: https://github.com/opentraffic/validator

**Comment by drewda** [comment]
Code will live at https://github.com/opentraffic/reporter-quality-testing-rig

**Comment by drewda** [comment]
Closing this, as all work is happening at https://github.com/opentraffic/reporter-quality-testing-rig
