### ISSUE TITLE
Kafka configurable message parsing

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/reporter#55]
right now the flink job expects one specific format for parsing messages from kafka or from file, it looks like this:

    date_string|id|X|X|X|accuracy|X|X|X|lat|lon|...

we can allow passing the flink job via an argument that tells it the format of the messages. the first to support will be `sv` separated value. for that we can say what is the separator and then what columns have the 5 important pieces of info: date, id, accuracy, lat, lon

there is the other important aspect of the date format but maybe we can defer this for the beginning.

after getting our feet wet with this step we should be able to move on to supporting things like json messages. to do this might not be that hard? flink uses generics to tell it what the messages are and we have a custom one. presumably we could make a few custom ones and throw that in the template.

**Comment by drewda** [comment]
Now that Reporter is only using Kafka, the message parsing will be configurable by sending different arguments into one of the Java-based Kafka programs.

We should document in the readme what the arguments are and gives examples for customizing each.
