### ISSUE TITLE
Bug: Timestamps with -1

### ISSUE THREAD

**Issue by kevinkreiser** [opentraffic/reporter#84]
sometimes the reports coming back from the python reporter have either `t0` or `t1` with a `-1` value. This causes the kafka java reporter code to make a time range for a given segment that is huge and crosses many time bins. That results in an enormous number of tiles which take eons to purge.

**Comment by dnesbitt61** [comment]
Fixed in valhalla/meili/traffic_segment_matcher. Awaiting next PPA
